language: node_js

cache:
  directories:
    - "Ëœ/.npm"

node_js:
  - '9'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - npm i -g truffle@4.1.6

script:
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
  on:
    branch: master
    repo: ipfsconsortium/IPFSConsortiumData
